# START_VERSION_BLOCK
VERSION_MAJOR = 1
VERSION_MINOR = 3
VERSION_BUILD = 2
VERSION_ALPHA = 3
# END_VERSION_BLOCK

__version__ = f"{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_BUILD}"
if VERSION_ALPHA:
    __version__ += f"a{VERSION_ALPHA}"
