name: Run UnitTests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'ovos_plugin_common_play/version.py'
      - 'requirements/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'ovos_plugin_common_play/version.py'
      - 'requirements/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev libssl-dev libfann-dev portaudio19-dev libpulse-dev
          python -m pip install -r requirements/test.txt
      - name: Install OCP
        run: |
          pip install -e .
      - name: Install test dependencies
        run: |
          pip install ./test/ovos-test-mycroft-audio-plugin
          pip install ./test/ovos-test-ocp-audio-plugin
      - name: Run unittests
        run: |
          pytest --cov=ovos_plugin_common_play --cov-report xml test/unittests
          # NOTE: additional pytest invocations should also add the --cov-append flag
          #       or they will overwrite previous invocations' coverage reports
          #       (for an example, see OVOS Skill Manager's workflow)
      - name: Run unittests with ovos-utils 0.0.38
        run: |
          pip install ovos-utils==0.0.38
          pytest --cov=ovos_plugin_common_play --cov-report xml test/unittests
      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        uses: codecov/codecov-action@v2